name: FoxBukkitPermissions
main: com.foxelbox.foxbukkit.permissions.FoxBukkitPermissions
version: 1.0.0
commands:
  reloadpermissions:
    description: Reloads permissions engine
    permission: foxbukkit.permissions.reload
    usage: /<command>
  pemu:
    description: Emulates permissions of lower rank
    permission: foxbukkit.permissions.emu
    usage: /<command>
