name: FoxBukkitPermissions
main: com.foxelbox.foxbukkit.permissions.FoxBukkitPermissions
version: 1.0.0
commands:
  fbreloadpermissions:
    description: Reloads permissions engine
    permission: foxbukkit.permissions.reload
    usage: /<command>