name: FoxBukkitPermissions
main: net.doridian.foxbukkit.permissions.FoxBukkitPermissions
version: 1.1.1
api-version: '1.20'
commands:
  reloadpermissions:
    description: Reloads permissions engine
    permission: foxbukkit.permissions.reload
    usage: /<command>
  pemu:
    description: Emulates permissions of lower rank
    permission: foxbukkit.permissions.emu
    usage: /<command>
